services:

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.0
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KC_HOSTNAME=localhost
      - KC_HTTP_PORT=8080
      - KC_HTTP_ADMIN_PORT=8081
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev

networks:
  default:
    name: appdev
    driver: bridge
