server:
  port: ${APP_PORT:8080}
  shutdown: graceful

spring:
  application:
    name: istio-sidecar-jwt-auth

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health}
  endpoint:
    health:
      show-details: ${ACTUATOR_SHOW_DETAILS:always}

jwt:
  jwk-set-uri: ${JWK_SET_URI:http://minikube:30080/realms/dev/protocol/openid-connect/certs}
  validation:
    enabled: ${JWT_VALIDATION_ENABLED:true}
